// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANEkEnGnydOBDPQWeUr4XOvlzFGyhT74o',
    appId: '1:661737652682:web:6158abc2372e1055de0f33',
    messagingSenderId: '661737652682',
    projectId: 'fbapp-fe360',
    authDomain: 'fbapp-fe360.firebaseapp.com',
    storageBucket: 'fbapp-fe360.appspot.com',
    measurementId: 'G-J354SNLQ8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM454t3Yq6fmo9ANkwphbCvBSAHdxIUiM',
    appId: '1:661737652682:android:37ce795012e40cabde0f33',
    messagingSenderId: '661737652682',
    projectId: 'fbapp-fe360',
    storageBucket: 'fbapp-fe360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcyCH2_79ASHp4vQrbg9QYDrBWXgSO6Q',
    appId: '1:661737652682:ios:1ac8170e46ea2a9ade0f33',
    messagingSenderId: '661737652682',
    projectId: 'fbapp-fe360',
    storageBucket: 'fbapp-fe360.appspot.com',
    iosClientId: '661737652682-l07u43t59c0cktcjtqtirdj44amcqb9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcyCH2_79ASHp4vQrbg9QYDrBWXgSO6Q',
    appId: '1:661737652682:ios:d8f3b73e498b25ccde0f33',
    messagingSenderId: '661737652682',
    projectId: 'fbapp-fe360',
    storageBucket: 'fbapp-fe360.appspot.com',
    iosClientId: '661737652682-0311gjp3th1socv7e6gj5uj8rifpmpok.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutter.RunnerTests',
  );
}
